  -- COMANDOS SQL SE DIVIDEM EM DUAS LINGUAGENS
  -- --------------------------------------------------
  -- DDL (Data Definition Language)
  -- => Comandos de definição do banco de dados
  -- Exemplos: CREATE DATABASE NAME
  --			  DROP DATABASE NAME
  --			  CREATE TABLE NAME (COLUNAS) 
  -- 		  DROP TABLE NAME 
  -- --------------------------------------------------
  -- DML (Data Manipulation Language)
  -- => Comandos de manipulação de dados
  -- Exemplos: SELECT COLUNAS FROM TABELA
  --		   INSERT INTO TABELA (COLUNAS) VALUES (VALORES)
  --		   DELETE FROM TABELA
  --  		   UPDATE TABELA SET COLUNAS
  